### ISSUE TITLE
Configure publishImage for GitLab Container registry. 

### ISSUE THREAD

**Issue by singh05** [ktorio/ktor-build-plugins#74]
How to setup publishing for GitLab container registry? I cant find any example.

**Comment by dcowley** [comment]
Hey @singh05, I've opened pull request #77 which will allow you to configure `publishImage` for external registries like GitLab container registry.

**Comment by Burtan** [comment]
This is still not working for me:

```
docker {
    jreVersion.set(JreVersion.JRE_17)
    localImageName.set("app-name")
    imageTag.set(version.toString())

    externalRegistry.set(DockerImageRegistry.externalRegistry(
        username = providers.environmentVariable("GITLAB_REGISTRY_USERNAME"),
        password = providers.environmentVariable("GITLAB_REGISTRY_PASSWORD"),
        project = provider { "projectname" },
        hostname = provider { "myregistry },
        namespace = provider { "namespace" }
    ))
}
```

throws

```
Execution failed for task ':app:jib'.
> Missing target image parameter, perhaps you should add a 'jib.to.image' configuration parameter to your build.gradle or set the parameter via the commandline (e.g. 'gradle jib --image <your image name>').
```

**Comment by Burtan** [comment]
DockerImageRegistry.externalRegistry() creates invalid urls for me, as it uses the value "image" as part of the url. Image always contains the localImageName and the imageTag seperated by the invalid character ":".

**Comment by e5l** [comment]
Thanks, merged!

**Comment by Stexxe** [comment]
https://github.com/ktorio/ktor-build-plugins/pull/96

**Comment by Burtan** [comment]
My commit was reverted although it was independent from the failing tests due to upgraded dependencies?

**Comment by e5l** [comment]
The problem was with the configuration cache. Now it is fixed and will be released in the next release. Sorry for the inconvenience.
